const data = {
    products:[
        {
            _id:'1',
            name:'Canon Printer',
            category:'Printers',
            image:'/images/printer.jpg',
            price:200,
            countInStock: 10,
            brand:'Nike',
            rating:4.2,
            numReviews:10,
            description: '2-year warranty',
        },
        {
            _id:'2',
            name:'Sony Audio Set',
            category:'Audioset',
            image:'/images/audioset1.jpg',
            price:300,
            countInStock: 5,
            brand:'Sony',
            rating:4.5,
            numReviews:10,
            description: '1 1/2-year warranty',
        },
        {
            _id:'3',
            name:'Lenovo wired mouse',
            category:'Mouse',
            image:'/images/mouse2.jpg',
            price:5,
            countInStock: 20,
            brand:'Lenovo',
            rating:4.0,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'4',
            name:'Longitech web cam',
            category:'Web Cam',
            image:'/images/web-cam.jpg',
            price:50,
            countInStock: 12,
            brand:'Longitech',
            rating:4.2,
            numReviews:10,
            description: 'focus clear. HD web camera',
        },
        {
            _id:'5',
            name:'Kingston Memmory SD Card',
            category:'Memmory SD Card',
            image:'/images/sd.jpg',
            price:10,
            countInStock: 30,
            brand:'Kingston',
            rating:4.5,
            numReviews:10,
            description: '2GB, 4GB, 8GB, 32GB, 64GB SD cards',
        },
        {
            _id:'6',
            name:'Asus VGA Card',
            category:'VGA Card',
            image:'/images/vgacard7.jpg',
            price:500,
            countInStock: 6,
            brand:'Asus',
            rating:4.5,
            numReviews:10,
            description: '2-year warranty',
        },
    ],
};
export default data;